server:
 port: 8081
 
spring:
 application:
  name: manosalaobrabackend

 datasource:
  url: jdbc:mysql://localhost:3306/manosalaobrabackend
  username: root
  password: oxfordSOMBRA123

 jpa:
  hibernate:
   ddl-auto: create
