server:
 port: 8081

spring:
 application:
  name: manosalaobrabackend
  
 datasource:
  url: jdbc:mysql://localhost:3306/manosalaobrabackend
  username: root
  password: Asbel!4897
  
 jpa:
  hibernate:
   #ddl-auto: create
   ddl-auto: update